
spring:
  application:
    name: FASTFOOD-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/patriciaorchelle/fastfood-centralization-config-files.git
          default-label: main
          username: patriciaorchelle
          password: patricia15/
          search-paths:
            - fastfood-registry-server
            - fastfood-gateway-server
        bootstrap: true

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
